### ISSUE TITLE
Extending the scope of NAPAM-CE to all Huawei VRP V8 devices.

### ISSUE THREAD

**Issue by michadom** [napalm-automation-community/napalm-ce#3]
I would lilke to propose this CloudEngine Switches driver to be extended to include all Huawei VRP V8 devices. I used this driver in a project and developed multiple methods to add support for other Huawei devices, routers specifically: NE40E-X2, NE40E-X16 and ATN 910C.

I proposed a new driver in networktocode.slack.com for all Huawei VRP V8 devices and Mircea suggest to ask you what do you think about extending this driver?

**Comment by mirceaulinic** [comment]
Hi @thddaniel. Have you seen @michadom's question above?

**Comment by thddaniel** [comment]
@michadom Sorry for not getting back to you sooner. You can make a pull request and I will add your name in contributors list. Thanks.

**Comment by michadom** [comment]
Hi @thddaniel 

Thanks for answering. I will take your answer as a "Yes, i am agreed to extend this driver and include all Huawei VRP V8 devices(Routers and Switches) ".

i'll get ready the codes and make the pull requests.

Regards,

**Comment by thddaniel** [comment]
Hi @mirceaulinic and @michadom, 
Just to let you know that I have updated the code to make it compatible with Napalm 3. Only support Python 3.6+ now.

**Comment by michadom** [comment]
Hi @thddaniel long time since i suggested extending this driver and never did a pull request. I'm back and i will be making many pull request using this account @codingnetworksb. This is my first pull request:

https://github.com/napalm-automation-community/napalm-ce/pull/15

Also i would like to be a maintainer of this driver. Could you let me be a maintainer?

Thanks and regards,

**Comment by thddaniel** [comment]
Sorry for the late reply.
![image](https://user-images.githubusercontent.com/7098631/180771622-0170d57c-9451-4b23-b21a-780434e68371.png)
