### ISSUE TITLE
not working with napalm > 3

### ISSUE THREAD

**Issue by zkzqzk** [napalm-automation-community/napalm-ce#5]
would you please consider make it with compatible with napalm > 3, because nornir_napalm need napalm > 3.     If we use nornir_napalm , we can't use napalm-ce at this time.

**Comment by thddaniel** [comment]
@zkzqzk Already support napalm 3, please check the [release](https://github.com/napalm-automation-community/napalm-ce/releases/tag/v0.2.0)

**Comment by zkzqzk** [comment]
I will try it out.

Thank you very much.

**Comment by thddaniel** [comment]
https://github.com/napalm-automation-community/napalm-ce/commit/70ba6341f3c0fc04ea58368e8c04068f8e872373

**Comment by thddaniel** [comment]
https://github.com/napalm-automation-community/napalm-ce/commit/70ba6341f3c0fc04ea58368e8c04068f8e872373
