### ISSUE TITLE
not install napalm-ce, error

### ISSUE THREAD

**Issue by jhhdez** [napalm-automation-community/napalm-ce#6]
Hey Everyone, I am brand new to this world and just trying to get my feet wet here. I am using the native ubuntu interface provided by windows. I have installed python and the necessary modules but when installing napalm-ce I get the following error, some assistance would be greatly appreciated.

Collecting napalm-ce
  Using cached napalm-ce-0.1.1.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /root/test/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zdc47ot2/napalm-ce_165033e4fce246b7a9fc121389d87870/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zdc47ot2/napalm-ce_165033e4fce246b7a9fc121389d87870/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qw84ta4f
         cwd: /tmp/pip-install-zdc47ot2/napalm-ce_165033e4fce246b7a9fc121389d87870/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zdc47ot2/napalm-ce_165033e4fce246b7a9fc121389d87870/setup.py", line 14, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-install-zdc47ot2/napalm-ce_165033e4fce246b7a9fc121389d87870/setup.py", line 14, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/88/62/eed5cd20062c80ca5f0b299f1a2c30410942c95f83d94f0fced238e125c3/napalm-ce-0.1.1.tar.gz#sha256=2347d4813f10a80ecaa74987c800aaf098f88ed150e642acc506c06496b52fcc (from https://pypi.org/simple/napalm-ce/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement napalm-ce
ERROR: No matching distribution found for napalm-ce

**Comment by thddaniel** [comment]
The problem was probably related to non-compatible versions of pip and pip-tools and was resolved by updating both pip and pip-tools. Can you fix it in the answer of [Mehant Kammakomati](https://stackoverflow.com/questions/62114945/attributeerror-parsedrequirement-object-has-no-attribute-req/62127548#62127548)?
